version: '3.8'

services:
  # 1. EL CARTERO (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto
    container_name: waterly_mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # 2. LA MEMORIA (InfluxDB)
  influxdb:
    image: influxdb:2.7
    container_name: waterly_db
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=waterly_org
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin
    volumes:
      - influxdb_data:/var/lib/influxdb2

  # 3. EL CEREBRO (Python API)
  waterly_brain:
    build: ./backend          
    container_name: waterly_api
    restart: always
    ports:
      - "8000:8000"           
    environment:
      - MQTT_BROKER=mosquitto
      - TB_HOST=thingsboard
      - PYTHONUNBUFFERED=1
    
    # AQUÍ ESTÁ EL TRUCO PARA QUE ESPERE:
    depends_on:
      mosquitto:
        condition: service_started
      thingsboard:
        condition: service_healthy  # <--- Solo arranca si TB está "sano"

  # 4. LA PLATAFORMA (ThingsBoard)
  thingsboard:
    image: thingsboard/tb-postgres
    container_name: waterly_tb
    restart: always
    ports:
      - "8080:9090"
      - "1884:1883"
    environment:
      - TB_QUEUE_TYPE=in-memory
    volumes:
      - tb_data:/data
      - tb_log:/var/log/thingsboard
    
    # DEFINIMOS QUÉ SIGNIFICA ESTAR "SANO":
    healthcheck:
      # Intenta descargar la página de login. Si responde, está vivo.
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/login"]
      interval: 10s       # Prueba cada 10 segundos
      timeout: 5s         # Si tarda más de 5s, falla
      retries: 20         # Inténtalo 20 veces antes de rendirte
      start_period: 60s   # Dale 1 minuto de gracia inicial para arrancar Java

volumes:
  influxdb_data:
  tb_data:
  tb_log: