version: '3.8'

services:
  # 1. EL CARTERO (Mosquitto)
  # Tu ESP32 seguirá conectándose aquí (Puerto 1883)
  mosquitto:
    image: eclipse-mosquitto
    container_name: waterly_mqtt
    restart: always
    ports:
      - "1883:1883"      # Puerto estándar MQTT
      - "9001:9001"      # WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # 2. LA MEMORIA (InfluxDB)
  # Aquí guardaremos el histórico masivo para la IA
  influxdb:
    image: influxdb:2.7
    container_name: waterly_db
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=waterly_org
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
    volumes:
      - influxdb_data:/var/lib/influxdb2

  # 3. EL CEREBRO (Python API)
  # Este conectará todo: Mosquitto <-> InfluxDB <-> ThingsBoard
  waterly_brain:
    build: ./backend          
    container_name: waterly_api
    restart: always
    ports:
      - "8000:8000"           
    depends_on:
      - mosquitto             
    environment:
      - MQTT_BROKER=mosquitto

  # 4. LA NUEVA PANTALLA (ThingsBoard)
  # Sustituye a Grafana. Panel de control profesional.
  thingsboard:
    image: thingsboard/tb-postgres
    container_name: waterly_tb
    restart: always
    ports:
      - "8080:9090"    # Entrarás por http://localhost:8080
      - "1884:1883"    # MQTT propio de TB (Puerto 1884 para no chocar con Mosquitto)
    environment:
      - TB_QUEUE_TYPE=in-memory
    volumes:
      - tb_data:/data
      - tb_log:/var/log/thingsboard

# Volúmenes persistentes (para no perder datos al reiniciar)
volumes:
  influxdb_data:
  tb_data:
  tb_log: